---
title: Welcome :D 
---

::: {.my-5}
## Hey, I’m Sabrina! 

I’m a first-semester **Master’s student in Business Analytics at [Baruch College](https://www.baruch.cuny.edu/)**.  This site showcases my work and projects from my course, *Basic Software Tools for Data Analytics.* 

I’m *from Brazil*, although both my parents are Chinese. In my free time, I *enjoy watching movies and TV shows, drawing*, and *playing games*.
:::

```{r}
#| echo: false
#| message: false
#| warning: false

if (!require("leaflet")) {
  options(repos = c(CRAN = "https://cloud.r-project.org"))
  install.packages("leaflet")
  stopifnot(require("leaflet"))
}

baruch_longitude <- -73.98333
baruch_latitude <- +40.75028

leaflet() |>
  addTiles() |>
  setView(baruch_longitude, baruch_latitude, zoom = 17) |>
  addPopups(
    baruch_longitude, baruch_latitude,
    "I am a Master's student at <b>Baruch College</b>!"
  )
```

```{r}
#| include: false
1 + 1
```
--------------
Last Updated: `r format(Sys.time(), "%A %m %d, %Y at %H:%M%p")`
